#! /bin/bash
echo 'docker build docker build --build-arg CUSTOM=$VAR -f $DOCKERFILE_PATH/min -t $DOCKER_REPO:min .'
echo $(pwd)
docker build docker build --build-arg CUSTOM=$VAR -f $DOCKERFILE_PATH/min -t $DOCKER_REPO:min .
docker push $DOCKER_REPO:min

