#! /bin/bash
cd min
echo docker build -f $DOCKERFILE_PATH -t $DOCKER_REPO:min .
echo $(pwd)
echo $DOCKERFILE_PATH
echo $DOCKER_REPO
echo $DOCKER_TAG
echo $IMAGE_NAME
docker build -f $DOCKERFILE_PATH -t $DOCKER_REPO:min .
docker push $DOCKER_REPO:min

